### ISSUE TITLE
[Issue]: Design an API v1 schema for external data

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/grants-ingest#114]
### Why is this issue important?

In order to provide useful, well-formed data to downstream consumers, this service should maintain a schema for published data that can be relied upon by consumers. Currently, the only way this service exposes data outwardly is through EventBridge events, so we should make sure the published data is formatted according to the schema.

Notes:
- The (DynamoDB) database is considered a private (as opposed to public) resource that is not directly accessible outside the this service, so its data need not conform to a particular API schema.
  - That said, there is no expectation that DynamoDB store data exactly as it is provided by any particular source. For example, storing date-based values as ISO-8601 strings rather than the `MMDDYYYY` format provided by grants.gov is perfectly acceptable. It's also fine if we want to persist data to DynamoDB according to this format, but the only motivation for doing so should be internal consistency.
- Since the only way this service currently exposes data is through EventBridge events, it would fine to implement schema compliance simply by mapping data from the source DynamoDB structure to that of the documented schema (i.e. we don't need an additional pipeline step).
- The version defined in the work for this ticket should be `v1`.

### Current State

Data published to EventBridge is more or less structured and formatted according to the upstream data provider (e.g. grants.gov).

### Expected State

Data published to EventBridge is structured and formatted according to the (v1) schema data model published by this service.

### Implementation Plan

1. Define data models suitable for representing grant opportunities in events published by this service.
2. Capture the data models in an [OpenAPI v3](https://spec.openapis.org/oas/v3.1.0) representation, saved to the repository as `openapi_v1.yaml`.
3. Update code wherever necessary to conform to the published schema.

Additional considerations:
- The API schema should be comprehensive; although examples in this ticket focus on "core"/common types related to grant opportunities, container schemas should also be considered (e.g. for representing "old" and "new" data views sent to the DynamoDB stream when an item is updated).
- We should make use of well-known standards for formatting data types. For example (as mentioned above), we should represent dates as ISO-8601 extended date strings (`YYYY-MM-DD`).
- Certain source values have a tendency to be brief and/or somewhat opaque; we should consider whether we want to deviate from source schemas in order to provide greater clarity in our own data. Examples:
  - The [grants.gov `OpportunityCategoryType`](https://www.grants.gov/web/grants/s2s/grantor/schemas/grants-common-types.html#OpportunityCategoryType) used for the `OpportunityCategory` field provides single-character string values of `C`, `D`, `E`, `M`, and `O` rather than more verbose strings of `Continuation`, `Discretionary`, `Earmark`, `Mandatory`, and `Other`. 
  - [The grants.gov `CostSharingOrMatchingRequirementType` type](https://www.grants.gov/web/grants/s2s/grantor/schemas/opportunity-detail.html#CostSharingOrMatchingRequirementsType) used for the `CostSharingOrMatchingRequirement` field is defined as a string with a max length of 3 characters (`Yes` or `No`) rather than as booleans.
  - The [grants.gov `FundingInstrument` type](https://www.grants.gov/web/grants/s2s/grantor/schemas/grants-funding-synopsis.html) used for the `FundingInstrumentType` field provides values of `CA`, `G`, `PC`, and `O` rather than `Cooperative Agreement`, `Grant`, `Procurement Contract`, or `Other`.
    - Note: We only deal with grants, so `G` is the only value we should ever see.
  - The [grants.gov `EligibleApplicantType` type](https://www.grants.gov/web/grants/s2s/grantor/schemas/grants-forecast-synopsis.html#EligibleApplicantType) used for the `EligibleApplicants` field is similarly based on a variety of 2-digit, numeric string "eligibility codes" rather than their corresponding descriptive values (e.g. `00` for `State Governments`, `05` for `Independent school districts`, etc.). See the link for all potential values.
  - The [grants.gov `FundingActivityCategory` type](https://www.grants.gov/web/grants/s2s/grantor/schemas/grants-forecast-synopsis.html#FundingActivityCategory) used for the `Category of Funding Activity` field is noted as "validated by web service but not in schema" in the grants.gov documentation, and is similarly comprised of abbreviated strings (e.g. `O` for `Other`, `AG` for `Agriculture`, etc.). See the link for all potential values.
  - All values are provided by grants.gov as strings (or containers of strings), including numeric values that represent dollar amounts, like `AwardCeiling` and `AwardFloor`. Would a decimal/float or custom "money" type ([like this](https://yakworks.github.io/gorm-rest-api/design-principles/schema/)) be better-suited for our schema?

**Comment by as1729** [comment]
Note: ensure that the additional "bill" field which comes from FFIS is added to the grants schema. This refers to the program/act that funds the grant.

**Comment by TylerHendrickson** [comment]
Closed by #143
