### ISSUE TITLE
Handle incoming FFIS emails delivered from SES

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/grants-ingest#61]
**DOD:** SES initially delivers FFIS emails (per the behavior outlined in #9) to a brand-new S3 bucket, and a new Lambda function moves newly-delivered emails to the "Grants Source Data" bucket (also according to the behavior specified in #9) after verifying the sender.

**Context:** This issue is part of the larger project focused on building out the Grants Ingest pipeline service. When investigating issues related to #9, we found that the Grants Ingest S3 bucket's policy's conditions around encrypted uploads (which require AES256 envelope encryption) are incompatible with SES-to-S3 email delivery, as the SES service only provides support for KMS-based encryption. After exploring options with AWS support, we found that it is also not possible to expand our bucket policy to facilitate _either_ AES256 ("SSE-S3") _or_ KMS, which was our original alternative option. The ultimate recommendation from AWS was to use a separate bucket that could be dedicated to email delivery use-cases.

**Implementation details:**
- Note: The domain of the dedicated recipient email address should be that of the Grants subdomain associated with the environment (e.g. @staging.grants.usdigitalresponse.org for staging, @grants.usdigitalresponse.org for prod).
- Create a new "Grants Ingest Emails" S3 bucket with the following settings:
    - Aborts incomplete multipart uploads after 1 day
    - Object versioning enabled
    - Has a bucket policy that only allows uploads (`PutObject`) from SES using KMS encryption (which should use the default `aws/ses` encryption key).
    - Expires (deletes) objects after 30 days.
- Create an SES receipt rule (e.g. modify the SES receipt rule created in #9) that:
  - Requires TLS
  - Scans matching emails for viruses
  - Routes matching emails to a new object in the "Grants Ingest Emails" S3 bucket, with an object key prefix prefix of `/ses/<dedicated inbox>/new` (where `<dedicated inbox>` is the SES-managed email address to which the email was sent).
- Create a new "Handle Incoming Emails" Lambda function that:
    - Allows invocation from the "Grants Ingest Emails" S3 bucket
    - Expects to receive an S3 Bucket Notification from the "Grants Ingest Emails" bucket for the `s3:ObjectCreated` event that indicates a new FFIS email has been processed as source data, with the following object key filters:
        - Prefix: `ses/<dedicated inbox>/new`
    - Has permission to upload objects (`PutObject`) to the "Grants Source Data" S3 bucket with a key based on the following pattern: `/sources/YYYY/mm/dd/ffis/raw.eml`, where the date is derived from the delivery date of the email.
    - When invoked, performs the following actions:
        - Inspects the sender and delivery date of the newly-delivered email specified in the invocation event.
        - Fails when the domain of the sender's address is not `ffis.org`.
        - After confirming the sender's address is `ffis.org`, copies the object specified in the invocation event from the source ("Grants Ingest Emails") bucket to the destination ("Grants Source Data") bucket, using the object key pattern specified above.

**Comment by TylerHendrickson** [comment]
@slapula Does this look correct to you?

**Comment by slapula** [comment]
Yes, this looks good and I believe we can close #10 as I think this work supersedes the work defined there.

**Comment by TylerHendrickson** [comment]
Closed by #67 #68 #69

**Comment by TylerHendrickson** [comment]
Reopening this, as it looks like the Lambda function responsible for moving received emails from the initial `email_delivery_bucket` to the `source_data_bucket` was never added. Until it is added, emails received from FFIS will sit in the original bucket indefinitely, and the `EnqueueFFISDownload` Lambda function will never be invoked.
